export const servicesConfig = {
  page: {
    heading: "Everything Your Home Needs",
    subheading: "From urgent emergencies to planned upgrades — we handle every plumbing situation.",
    badge: "Licensed & Insured",
  },
  categories: [
    { id: "all", label: "All Services" },
    { id: "emergency", label: "Emergency" },
    { id: "repair", label: "Repairs" },
    { id: "installation", label: "Installation" },
    { id: "maintenance", label: "Maintenance" },
  ],
  items: [
    {
      id: "emergency-plumbing", slug: "emergency-plumbing", category: "emergency",
      icon: "AlertTriangle", name: "Emergency Plumbing",
      shortDesc: "Burst pipes, major leaks, flooding — we respond in under 60 minutes.",
      fullDesc: "Plumbing emergencies don't wait for business hours. Our emergency team is on standby 24/7, ready to respond to burst pipes, severe leaks, sewer backups, and any urgent situation threatening your home.",
      highlights: ["Response in under 60 minutes", "Available 24/7 including public holidays", "No extra charge for after-hours", "Immediate damage control"],
      badge: "24/7", featured: true,
      cta: { label: "Call Now — It's Urgent", href: "tel:+61298765432" },
    },
    {
      id: "blocked-drains", slug: "blocked-drains", category: "repair",
      icon: "Waves", name: "Blocked Drains",
      shortDesc: "Slow drains, backups and clogs cleared fast — guaranteed.",
      fullDesc: "Blocked drains are one of the most common plumbing problems in Sydney. We use professional hydro-jetting equipment to clear blockages completely and prevent them returning.",
      highlights: ["Hydro-jetting for complete clearing", "CCTV camera inspection available", "Kitchen, bathroom and sewer drains", "Preventive treatment options"],
      badge: "Most Popular", featured: true,
      cta: { label: "Book Drain Service", href: "/booking" },
    },
    {
      id: "leak-repair", slug: "leak-repair", category: "repair",
      icon: "Droplets", name: "Leak Detection & Repair",
      shortDesc: "Find hidden leaks before they cause thousands in damage.",
      fullDesc: "Even a small leak can cause serious water damage over time. Our non-invasive detection technology finds hidden leaks in walls, floors, and underground — without tearing your home apart.",
      highlights: ["Non-invasive detection technology", "Under-slab and wall leaks", "Water main and supply line repair", "Same-day repair available"],
      badge: null, featured: true,
      cta: { label: "Schedule Inspection", href: "/booking" },
    },
    {
      id: "hot-water", slug: "hot-water", category: "installation",
      icon: "Flame", name: "Hot Water Systems",
      shortDesc: "Installation, repair, and replacement — tank and continuous flow.",
      fullDesc: "Whether your hot water system is failing, inefficient, or you are ready to upgrade to a continuous flow system, our certified plumbers handle all makes and models.",
      highlights: ["Tank and continuous flow systems", "Same-day installation available", "Energy-efficient upgrades", "All brands serviced"],
      badge: null, featured: false,
      cta: { label: "Get a Quote", href: "/booking" },
    },
    {
      id: "pipe-services", slug: "pipe-services", category: "installation",
      icon: "Wrench", name: "Pipe Repair & Replacement",
      shortDesc: "Re-piping, new installations, and pipe repair done right.",
      fullDesc: "From single pipe repairs to full home re-piping, we work with copper, PVC, and PEX materials. Our team ensures every connection is watertight and code-compliant.",
      highlights: ["Full home re-piping", "Copper, PEX and PVC", "Code-compliant to AS 3500", "Pressure testing on completion"],
      badge: null, featured: false,
      cta: { label: "Get a Quote", href: "/booking" },
    },
    {
      id: "sewer-services", slug: "sewer-services", category: "repair",
      icon: "Filter", name: "Sewer & Drainage",
      shortDesc: "CCTV inspections, repairs, and trenchless replacement.",
      fullDesc: "Sewer problems are serious. We use CCTV camera inspection to diagnose sewer line issues and offer trenchless repair options that save your lawn while fixing the problem permanently.",
      highlights: ["CCTV camera inspection", "Trenchless repair options", "Root removal", "Full sewer replacement"],
      badge: null, featured: false,
      cta: { label: "Book Inspection", href: "/booking" },
    },
    {
      id: "bathroom-kitchen", slug: "bathroom-kitchen", category: "installation",
      icon: "Bath", name: "Bathroom & Kitchen Plumbing",
      shortDesc: "Fixtures, tapware, toilets, sinks — installation and repair.",
      fullDesc: "Renovating or replacing fixtures? We handle all bathroom and kitchen plumbing including toilet installation, tapware replacement, kitchen sinks, and full renovation rough-in.",
      highlights: ["Tapware and fixture replacement", "Toilet installation and repair", "Kitchen sink and dishwasher", "Full renovation plumbing"],
      badge: null, featured: false,
      cta: { label: "Book Installation", href: "/booking" },
    },
    {
      id: "inspection", slug: "inspection", category: "maintenance",
      icon: "Search", name: "Plumbing Inspection",
      shortDesc: "Comprehensive home plumbing checkup — catch issues early.",
      fullDesc: "Our 30-point plumbing inspection covers every system in your home. Ideal for new homebuyers, annual checkups, or pre-sale inspections. Written report provided.",
      highlights: ["30-point inspection checklist", "Written report provided", "Ideal for home buyers and sellers", "CCTV inspection add-on available"],
      badge: "Recommended Annually", featured: false,
      cta: { label: "Book Inspection", href: "/booking" },
    },
  ],
  homepageFeaturedIds: ["emergency-plumbing", "blocked-drains", "leak-repair", "hot-water", "pipe-services", "sewer-services"],
};