export const siteConfig = {
  brand: {
    name: "FlowMate Plumbing",
    tagline: "Sydney's Most Trusted Plumbers",
    phone: "0412 345 678",
    phoneDisplay: "(02) 9876 5432",
    phoneHref: "tel:+61298765432",
    email: "hello@flowmateplumbing.com.au",
    address: "7 Plumber Lane, Parramatta NSW 2150",
    abn: "ABN: 12 345 678 901",
    license: "NSW Lic. #PL-384721",
    founded: "2009",
    serviceArea: "Greater Sydney Area",
    emergencyAvailable: true,
    logo: { text: "FlowMate", accent: "Plumbing" },
  },
  contact: {
    phone: "(02) 9876 5432",
    phoneHref: "tel:+61298765432",
    email: "hello@flowmateplumbing.com.au",
    hours: {
      weekdays: "Mon–Fri: 7:00 AM – 6:00 PM",
      weekends: "Sat–Sun: 8:00 AM – 5:00 PM",
      emergency: "24/7 Emergency Service Available",
    },
  },
  nav: {
    links: [
      { label: "Services", href: "/services" },
      { label: "About", href: "/about" },
      { label: "Reviews", href: "/reviews" },
      { label: "Plans", href: "/plans" },
      { label: "Emergency", href: "/emergency", badge: "24/7" },
    ],
    cta: { label: "Book a Plumber", href: "/booking" },
  },
  hero: {
    badge: "⭐ Sydney's #1 Plumber · 3,200+ 5-Star Reviews",
    headline: ["Sydney's Most", "Trusted Plumbers"],
    subheadline: "Fast response. Upfront pricing. Guaranteed workmanship. We're the team you call when it matters most.",
    primaryCta: { label: "Book a Plumber", href: "/booking" },
    secondaryCta: { label: "Call Now", href: "tel:+61298765432" },
    trustNote: "✓ No call-out fees  ✓ Same-day available  ✓ Licensed & insured",
    stats: [
      { value: "15+", label: "Years in Sydney" },
      { value: "3,200+", label: "Happy Customers" },
      { value: "98%", label: "5-Star Reviews" },
      { value: "< 60min", label: "Emergency Response" },
    ],
  },
  trustBar: {
    items: [
      { label: "Licensed & Insured" },
      { label: "Same-Day Service" },
      { label: "Upfront Pricing" },
      { label: "4.9-Star Rated" },
      { label: "10-Year Guarantee" },
    ],
  },
  howItWorks: {
    headline: "Booked in 60 Seconds",
    subheadline: "Getting help has never been simpler.",
    steps: [
      { step: "01", title: "Book or Call", description: "Use our online form or call us. We're always available.", icon: "Phone" },
      { step: "02", title: "We Confirm & Dispatch", description: "A certified plumber is confirmed and on their way within minutes.", icon: "CheckCircle" },
      { step: "03", title: "Get an Upfront Quote", description: "No work starts until you approve the price. Always.", icon: "FileText" },
      { step: "04", title: "Problem Solved", description: "Fixed right the first time, backed by our written guarantee.", icon: "Trophy" },
    ],
  },
  guarantees: [
    { title: "Upfront Pricing", description: "You approve the quote before any work begins. No surprise bills." },
    { title: "Licensed & Insured", description: "All plumbers hold current NSW licences with full insurance coverage." },
    { title: "Workmanship Warranty", description: "Every repair backed by a written 12-month workmanship guarantee." },
  ],
  emergency: {
    headline: "Plumbing Emergency?",
    subheadline: "Don't wait. Every minute costs you more. Call for immediate dispatch.",
    badge: "Available 24/7 · 365 days",
    phoneDisplay: "(02) 9876 5432",
    phoneHref: "tel:+61298765432",
    responseClaim: "We dispatch within 15 minutes.",
    steps: [
      { step: "01", title: "Call the Emergency Line", description: "Our emergency team picks up immediately — day or night." },
      { step: "02", title: "Immediate Dispatch", description: "A licensed plumber is dispatched within 15 minutes of your call." },
      { step: "03", title: "Problem Solved Fast", description: "95% of emergency jobs completed in a single visit." },
    ],
    safetyTips: [
      "Shut off the main water valve immediately",
      "Turn off electricity in affected areas if safe to do so",
      "Document damage with photos for insurance",
      "Clear the area and keep children and pets away",
      "Do not use toilets or sinks in the affected area",
    ],
    coverageAreas: ["Parramatta", "Blacktown", "Penrith", "Liverpool", "Campbelltown", "Hornsby", "Chatswood", "Manly", "Bondi", "Newtown", "Strathfield", "Burwood", "Auburn", "Fairfield", "Bankstown", "Hurstville"],
    emergencyTypes: [
      { icon: "ZapOff", title: "Burst Pipes", description: "Immediate water shutoff and pipe repair to stop flooding before it causes structural damage." },
      { icon: "Droplets", title: "Sewage Backups", description: "A serious health hazard — we treat this as highest priority and respond immediately." },
      { icon: "AlertTriangle", title: "Major Leaks", description: "Uncontrolled leaks causing water damage to walls, floors, or ceilings." },
      { icon: "Flame", title: "Hot Water Failure", description: "No hot water or water heater leaking — same-day assessment and replacement." },
      { icon: "Waves", title: "Flooding", description: "Water pooling from a plumbing failure — find and stop the source fast." },
      { icon: "Wind", title: "Gas Concerns", description: "Smell gas near appliances? Leave home immediately and call us — we're ATCO certified." },
    ],
  },
  ctaSection: {
    headline: "Ready to Fix It?",
    subheadline: "Book online in 60 seconds or call us now. Same-day slots available.",
    primaryCta: { label: "Book a Plumber", href: "/booking" },
    secondaryCta: { label: "Call (02) 9876 5432", href: "tel:+61298765432" },
    note: "No commitment. Free quote on-site. Cancel anytime.",
  },
  footer: {
    tagline: "Reliable plumbing. Honest pricing. Always on time.",
    links: {
      Services: [
        { label: "Emergency Plumbing", href: "/services/emergency-plumbing" },
        { label: "Blocked Drains", href: "/services/blocked-drains" },
        { label: "Leak Detection", href: "/services/leak-repair" },
        { label: "Hot Water Systems", href: "/services/hot-water" },
        { label: "Pipe Repair", href: "/services/pipe-services" },
        { label: "Sewer & Drainage", href: "/services/sewer-services" },
        { label: "Bathroom Plumbing", href: "/services/bathroom-kitchen" },
        { label: "Plumbing Inspection", href: "/services/inspection" },
      ],
      Company: [
        { label: "About Us", href: "/about" },
        { label: "Reviews", href: "/reviews" },
        { label: "Maintenance Plans", href: "/plans" },
        { label: "Contact", href: "/contact" },
        { label: "Careers", href: "/careers" },
      ],
      Legal: [
        { label: "Privacy Policy", href: "/privacy" },
        { label: "Terms of Service", href: "/terms" },
        { label: "License Info", href: "/license" },
      ],
    },
  },
  seo: {
    titleTemplate: "%s | FlowMate Plumbing Sydney",
    defaultTitle: "FlowMate Plumbing | Sydney's #1 Trusted Plumber",
    description: "Fast, reliable plumbing in Sydney. Emergency service 24/7. Transparent pricing, licensed & insured. Book online or call now.",
  },
};
export default siteConfig;